Tickets/dm 38695
lsst-dm/cm_tools pull request #51
Opened 2023-04-13 22:15 UTC by eacharles

2023-04-13 23:29 UTC, fritzm approved these changes
LGTM

2023-04-14 00:38 UTC, eigerx requested changes

2023-04-14 00:38 UTC, eigerx commented on src/lsst/cm/tools/db/sqlalch_interface.py
> +            StatusEnum.rescueable,
This is missing superseded!

2023-04-14 00:38 UTC, eigerx commented on src/lsst/cm/tools/db/sqlalch_interface.py
> +            StatusEnum.rescueable,
🥉

2023-04-14 00:42 UTC, eigerx approved these changes
congratulations!

2023-04-14 00:42 UTC, merged